# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: univmeet_development
  username: "postgres"
  hostname: localhost
  port: 5432

test:
  <<: *default
  database: univmeet_test
  username: "postgres"
  hostname: localhost
  port: 5432

production:
  <<: *default
  database: univmeet_production
  username: univmeet
  password: <%= ENV['UNIVMEET_DATABASE_PASSWORD'] %>
